Error out when we cannot csup the sources.

diff --git a/builder_scripts/cvsup_current b/builder_scripts/cvsup_current
--- a/builder_scripts/cvsup_current
+++ b/builder_scripts/cvsup_current
@@ -169,7 +169,12 @@ fi
 if [ -z "${GIT_REPO_BSDINSTALLER:-}" ]; then
 	echo -n ">>> Fetching BSDInstaller using CVSUP..."
 	(csup -b $BASE_DIR ${BUILDER_SCRIPTS}/bsdinstaller-supfile) 2>&1 | egrep -B3 -A3 -wi '(error)'
-	echo "Done!"
+	if [ "$?" = "1" ]; then
+		echo "!!!! An error occured while fetching BSDInstaller sources!"
+		sleep 65535
+	else 
+		echo "Done!"
+	fi
 	./cvsup_bsdinstaller
 else 
 	echo -n ">>> Fetching BSDInstaller using GIT..."
@@ -214,7 +219,12 @@ done
 BASENAMESUPFILE=`basename $SUPFILE`
 echo -n ">>> Obtaining FreeBSD sources ${BASENAMESUPFILE}..."
 (csup -b $SRCDIR -h `cat /var/db/fastest_cvsup` ${SUPFILE}) 2>&1 | egrep -B3 -A3 -wi '(error)'
-echo "Done!"
+if [ "$?" = "1" ]; then
+	echo "!!!! An error occured while fetching BSDInstaller sources!"
+	sleep 65535
+else 
+	echo "Done!"
+fi
 
 echo ">>> Removing old patch rejects..."
 find $SRCDIR -name "*.rej" -exec rm {} \;
