Turn off BSDInstaller check for time being

diff --git a/builder_scripts/cvsup_current b/builder_scripts/cvsup_current
--- a/builder_scripts/cvsup_current
+++ b/builder_scripts/cvsup_current
@@ -169,12 +169,12 @@ fi
 if [ -z "${GIT_REPO_BSDINSTALLER:-}" ]; then
 	echo -n ">>> Fetching BSDInstaller using CVSUP..."
 	(csup -b $BASE_DIR ${BUILDER_SCRIPTS}/bsdinstaller-supfile) 2>&1 | egrep -B3 -A3 -wi '(error)'
-	if [ "$?" = "1" ]; then
-		echo "!!!! An error occured while fetching BSDInstaller sources!"
-		sleep 65535
-	else 
+	#if [ "$?" = "1" ]; then
+	#	echo "!!!! An error occured while fetching BSDInstaller sources!"
+	#	sleep 65535
+	#else 
 		echo "Done!"
-	fi
+	#fi
 	./cvsup_bsdinstaller
 else 
 	echo -n ">>> Fetching BSDInstaller using GIT..."
